name: "PlatformTest"

on:
  push:
    branches: [ platform-test ]

jobs:
  linux-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: run the toolkit
      run: bash tests/PDGToolkit.CrossPlatformTests/unix.sh

  mac-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: run the toolkit
      run: bash tests/PDGToolkit.CrossPlatformTests/unix.sh