name: "Semver"

on:
  push:
    branches: [ feature/13-semver ]

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: "Get Semantic Version"
      uses: paulhatch/semantic-version@v3.3
      id: semver
      with:
        # The prefix to use to identify tags
        branch: "feature/13-semver"
        # The prefix to use to identify tags
        tag_prefix: "v"
        # A string which, if present in a git commit, indicates that a change represents a
        # major (breaking) change, supports regular expressions wrapped with '/'
        major_pattern: "(MAJOR)"
        # Same as above except indicating a minor change, supports regular expressions wrapped with '/'
        minor_pattern: "(MINOR)"
        # A string to determine the format of the version output
        format: "${major}.${minor}.${patch}"
        # Indicate whether short tags like 'v1' should be supported. If false only full
        # tags like 'v1.0.0' will be recognized.
        short_tags: true
        # If this is set to true, *every* commit will be treated as a new version.
        bump_each_commit: false
    
    - name: "Display semver"
      run: |
        echo $VERSION
      env: 
        VERSION: ${{ steps.semver.outputs.version }}

    - name: "Create a new tag"
      run: |
        git tag "v$VERSION"
        git push --tags
      env: 
        VERSION: ${{ steps.semver.outputs.version }}



